[package]
name = "bited-rust"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
godot = "0.4.5"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.11"
