name: check
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      godot: ${{ steps.changes.outputs.godot }}
      rust: ${{ steps.changes.outputs.rust }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/check.yml'
              - 'rust/**'
            godot:
              - 'flake.nix'
              - 'flake.lock'
              - '.github/workflows/check.yml'
              - 'godot/{addons,components}'
  fmt:
    runs-on: ubuntu-latest
    needs: changes
    outputs:
      godot: ${{ needs.changes.outputs.godot }}
      rust: ${{ needs.changes.outputs.rust }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake check
  godot-lint:
    runs-on: ubuntu-latest
    needs: fmt
    if: needs.fmt.outputs.godot == 'true'
    defaults:
      run:
        working-directory: godot
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop -c 'bash' -c 'gdlint components'
  rust-lint:
    runs-on: ubuntu-latest
    needs: fmt
    if: needs.fmt.outputs.rust == 'true'
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop -c 'bash' -c 'cargo clippy'
  build:
    runs-on: ubuntu-latest
    needs: fmt
    if: needs.fmt.outputs.rust == 'true' || needs.fmt.outputs.godot == 'true'
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix build .#build-check
